name: wishtag_web
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 3.11.0
  flutter_dotenv: 5.2.1
  cupertino_icons: ^1.0.8
  flutter_screenutil: 5.9.3
  firebase_auth: 5.4.2
  flutter_riverpod: 2.6.1
  auto_route: 9.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: 2.4.14
  auto_route_generator: 9.3.1

flutter:
  uses-material-design: true

