class DataMock {
  static List<String> get recentActivities => [
        'John Doe banned user asda@asdas.com',
        'Kriss resolved ticket #123',
        'James resolved ticket #213',
        'Kriss resolved ticket #1113',
        'Michael resolved ticket #41',
        'Sam resolved ticket #21',
        'Rick resolved ticket #322',
        'Alice approved new feature request ticket #504',
        'Bob updated system settings',
        'Charlie removed inactive user dave@example.com',
        'Diana created new ticket #789',
        'Evan reviewed ticket #456',
        'Fiona reset user password for user frank@example.com',
        'George closed ticket #890',
        'Helen escalated ticket #567',
        'Ivan resolved ticket #678',
        'Julia added new admin role to user kate@example.com',
        'Kevin assigned ticket #234 to team',
        'Laura flagged ticket #345 for review',
        'Mike approved pending merge request #112',
        'Nina updated ticket #456 with new details',
        'Oliver banned user oscar@example.com',
        'Patricia resolved ticket #789',
        'Quentin commented on ticket #890',
        'Rachel updated security settings',
        'Sam re-opened ticket #901',
        'Tina archived ticket #101',
        'Uma updated user profile for victor@example.com',
        'Wendy resolved ticket #1122',
        'Xander created a new feature ticket #1313',
        'Yvonne updated ticket #1414',
        'Zack approved request for system update',
        'Aaron reviewed ticket #1515',
        'Bella changed account status for user carl@example.com',
        'Cody resolved ticket #1616',
        'Dana escalated ticket #1717 to management',
        'Eli updated documentation for ticket #1818',
        'Faith closed ticket #1919',
        'Gavin approved new pricing model',
        'Holly resolved ticket #2020',
        'Isaac updated ticket #2121 with comments',
        'Jasmine removed spam user spam@example.com',
        'Kyle approved merge request #2222',
        'Liam updated server configurations',
        'Mia resolved ticket #2323',
        'Noah reviewed and closed ticket #2424',
        'Olivia updated permissions for group admins',
        'Peter resolved ticket #2525',
        'Rita approved new user registration for VIP',
        'Steve resolved ticket #2626',
      ];
}
