name: Build check

on:
  pull_request:

jobs:
  build_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build Check
        id: build
        continue-on-error: true
        run: |
          set +e
          build_log=$(flutter build web --release 2>&1)
          exit_code=$?
          echo "build_log<<EOF" >> $GITHUB_OUTPUT
          echo "$build_log" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
          exit $exit_code

      - name: Report Build Failure
        if: ${{ steps.build.outcome == 'failure' }}
        uses: actions/github-script@v7
        env:
          BUILD_LOG: ${{ steps.build.outputs.build_log }}
        with:
          script: |
            const buildLog = process.env.BUILD_LOG || 'No output captured.';
            const commentBody = `### Build Failed
  <details>
  <summary>Click to view build logs</summary>
  
  \`\`\`
  ${buildLog}
  \`\`\`
  
  </details>
  
  Please check the build logs above for details.`;
  await github.rest.issues.createComment({
owner: context.repo.owner,
repo: context.repo.repo,
issue_number: context.issue.number,
body: commentBody
});
  process.exit(1);
