- name: Report Build Failure
  if: ${{ steps.build.outcome == 'failure' }}
  uses: actions/github-script@v7
  env:
    BUILD_LOG: ${{ steps.build.outputs.build_log }}
  with:
    script: |
      const buildLog = process.env.BUILD_LOG || 'No output captured.';
      const commentBody = `### Build Failed\n\n<details>\n<summary>Click to view build logs</summary>\n\n\`\`\`\n${buildLog}\n\`\`\`\n\n</details>\n\nPlease check the build logs above for details.`;
      await github.rest.issues.createComment({
        owner: context.repo.owner,
        repo: context.repo.repo,
        issue_number: context.issue.number,
        body: commentBody
      });
      process.exit(1);
