name: Build check

on:
  pull_request:

jobs:
  build_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'
          cache: true

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Code generation
        run: dart run build_runner build

      - name: Check build
        run: |
          flutter build web --release \
            ${{ secrets.PROD_BUILD_ARGS }}

